### ISSUE TITLE
Clearing workshop folder

### ISSUE THREAD

**Issue by khakers** [Unturned-Official-Discord/U3-Support-Knowledgebase#5]

**Comment by Tech15** [comment]
To clear your workshop files go to 
X:\Program Files (x86)\Steam\steamapps\workshop\content\304930
X is the drive that you have the game installed on, you can see what your drive is labelled as by clicking "This PC" after using the windows key and E shortcut, mine has C: in it so I put 
C:\Program Files (x86)\Steam\steamapps\workshop\content\304930 in my directory and it sent me to a folder with presumably alot of mods, you just highlight all of these folders and hit delete on your keyboard. Congratulations, you wiped your mods folder
